Db postgres sqlalchemy alembic docker
kreoshine/kreoshine pull request #16
Opened 2023-04-21 20:00 UTC by pillager-SB

2023-04-22 13:47 UTC, valvandor requested changes

2023-04-22 13:47 UTC, valvandor commented on backend/requirements.txt
> +alembic==1.10.3
Тут лучше опустить указание конкретной версии

2023-04-22 13:47 UTC, valvandor commented on docker-compose.yml
> +      DB_PASSWORD: 1234
Чувствительные данные надо будет генерировать через dynaconf.
Пока можно просто создать issue, чтобы эта задача была не забыта

2023-04-22 13:47 UTC, valvandor commented on backend/alembic/versions/fb6d591ccea6_table1.py
> +down_revision = '8a6f19d30c1a'
А зачем нам две миграции?
Надо оставить одну с корректной структурой

2023-04-22 15:37 UTC, HappySeien commented on backend/alembic/versions/fb6d591ccea6_table1.py
> +down_revision = '8a6f19d30c1a'
Тут к сожалению получилось так что алембик не цеплял модели в первую миграцию, поэтому пришлось делать описание руками, вторая дополняет пропущенное)

2023-04-23 12:10 UTC, valvandor commented on backend/app/settings.py
> +config_path = BASE_DIR / "config" / "config.yaml"
А что это за конфиг?

2023-04-23 14:03 UTC, closed without merging