recent changes to database tables
kreoshine/kreoshine pull request #21
Opened 2023-05-19 08:42 UTC by pillager-SB

2023-05-19 09:02 UTC, valvandor requested changes

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    id: Mapped[int] = mapped_column(primary_key=True)
такие идентификаторы лучше называть с префиксом от имени таблицы, например service_id

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    """
пока можно обойтись без этой таблицы

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    short_deskription: Mapped[str] = mapped_column(nullable=False)
опечатка в названии

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    """
лучше если docstring будет в англоязычной форме

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        "received", "discussed", "in progress", "closed", name="status_enum"))
давай откажемся от валидации на уровне БД и будем это делать на уровне приложения. и оставить обычный VARCHAR тогда

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    executor: Mapped[int] = mapped_column(ForeignKey("users.id"), default=1)
на данный момент это будет лишняя логика, пользоваться планируется пока в одиночку в качестве админа

2023-05-19 09:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    phone: Mapped[str] = mapped_column(nullable=False)
лучше оставить необязательным поле

2023-05-19 09:19 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    """
Ok! Убираю

2023-05-19 09:25 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    id: Mapped[int] = mapped_column(primary_key=True)
Изменяю

2023-05-19 09:27 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    short_deskription: Mapped[str] = mapped_column(nullable=False)
Исправил

2023-05-19 09:27 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    """
Перевел

2023-05-19 19:11 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +        "received", "discussed", "in progress", "closed", name="status_enum"))
Виталий, поясни plz, о какой валидации тут идет речь?

2023-05-19 19:12 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    executor: Mapped[int] = mapped_column(ForeignKey("users.id"), default=1)
тогда поле executor убираю вообще?

2023-05-19 19:15 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    phone: Mapped[str] = mapped_column(nullable=False)
убрал с phone nullable=False

2023-05-19 20:07 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        "received", "discussed", "in progress", "closed", name="status_enum"))
Имеется ввиду что мы на уровне приложения будем валидировать данные приходящие с фронта. Условно, будут разрешено некоторые значения, по которым фронт может изменить/сохранить данные. При неверном значении будет ошибка. Но это будет контракт между фронтом и бэком, поэтому ошибка будет исключена. 

Таким образом мы легко сможем добавить любой дополнительный статус если он появится.

Как пример валидатора можно посмотреть библиотеку Cerberus

2023-05-19 20:08 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    executor: Mapped[int] = mapped_column(ForeignKey("users.id"), default=1)
Да, давай пока будем стремиться реализовать только необходимое

2023-05-22 08:51 UTC, valvandor requested changes

2023-05-22 08:51 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    users_mail: Mapped[str] = mapped_column(nullable=False)
здесь пожалуй излишне использовать приставку в виде 'users_'

2023-05-22 08:51 UTC, valvandor commented on backend/db/models_configuration/models.py
>      service_id: Mapped[int] = mapped_column(primary_key=True)
как тебе идея сделать название таблицы sale_items?
так будет более понятно к чему это сущность относится.

2023-05-22 08:51 UTC, valvandor commented on backend/db/models_configuration/models.py
>      client_request_id: Mapped[int] = mapped_column(primary_key=True)
для единообразия лучше, если названия таблиц будут в множественном числе, а модели — в единственном

2023-05-22 08:51 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    theme: Mapped[int] = mapped_column(ForeignKey("service.service_id"))
давай это поле будет необязательным и будет ссылаться на имя "продаваемого объекта".  Фронт может и не знать идентификаторов, а вот имя ему будет известно
имя колонки можно сделать sale_item_name

2023-05-22 11:39 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      service_id: Mapped[int] = mapped_column(primary_key=True)
Так там же нет продаж, есть услуги, service в этом случае как раз самое оно, разве нет?

2023-05-22 12:00 UTC, valvandor commented on backend/db/models_configuration/models.py
>      service_id: Mapped[int] = mapped_column(primary_key=True)
просто это название service очень перекликается с общим названием. Хотелось бы избежать этого. а как насчёт trade_items?

2023-05-22 12:07 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      client_request_id: Mapped[int] = mapped_column(primary_key=True)
Сделал так, потому что на одном из курсов было сказано, что название таблиц в единственном числе - это хороший тон в написании бд, исключение - таблица users, и то вроде как в силу традиций(В примерах к SQLAlchemy все названия в единственном числе).
Названия, классов/таблиц одинаковые и отличаются только использованием прописных/заглавных букв согласно PEP-8, я сейчас не вспомню где и как, но это использовалось в логике. типа ИмяМодели.low() = имя_таблицы

2023-05-22 12:16 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    theme: Mapped[int] = mapped_column(ForeignKey("service.service_id"))
Опять же мы не продаем ничего на странице, в этом поле просто информация, с какой страницы клиент отправил свое сообщение, если мы ее никак не обрабатываем и не используем - можно и просто название услуги там сохранять

2023-05-22 12:18 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    users_mail: Mapped[str] = mapped_column(nullable=False)
users - это я да, погорячился))), должно быть user! Аналогичные поля есть у клиента

2023-05-22 12:19 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      service_id: Mapped[int] = mapped_column(primary_key=True)
да как-то опять про торговлю...

2023-05-22 12:22 UTC, valvandor requested changes

2023-05-22 12:22 UTC, valvandor commented on backend/db/models_configuration/models.py
>      users_id: Mapped[int] = mapped_column(primary_key=True)
в качестве идентификатора лучше использовать uuid4 (это будет строкой)

2023-05-22 12:22 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        "closed"
валидные значения будут обозначены в описании API сервиса, тут лучше убрать это

2023-05-22 12:22 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    theme: Mapped[int] = mapped_column(ForeignKey("service.service_id"))
если будем делать привязку к объекту продажи, то давай сделаем поле вида request_subject_id (без указания foreign key и необязательным). Добавляя связь мы должны будем более внимательно следить за удалением (хоть такого и не планируется, но все же) или же прописать правила on_cascade/on_delete более явно для внешнего ключа. Также вряд-ли нам что-то понадобится из таблицы продаваемых объектов (или как сейчас услуг) в связке с запросом. В будущем можно будет добаваить при необходимости

2023-05-22 12:27 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    theme: Mapped[int] = mapped_column(ForeignKey("service.service_id"))
Согласен! Ну, так-то вообще не понятно, что нам такого уникального даст это поле, если клиент в сообщении и так опишет свои хотелки на определенную услугу?

2023-05-22 12:29 UTC, valvandor commented on backend/db/models_configuration/models.py
>      client_request_id: Mapped[int] = mapped_column(primary_key=True)
вот [тут](https://oracle-patches.com/db/sql/%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0-t-sql-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F#:~:text=%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%B1%D1%8B%D1%82%D1%8C%20%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B0%20%D0%B2,%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%20%D0%B1%D1%83%D0%B4%D0%B5%D1%82%20%D0%BF%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D0%BE%D0%B4%D0%BD%D0%B0%20%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B0.&text=%D0%9D%D0%B5%20%D0%BD%D1%83%D0%B6%D0%BD%D0%BE%20%D0%BD%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%82%D1%8C%20%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B%20%D0%B8%D0%BB%D0%B8,%D0%B4%D1%80%D1%83%D0%B3%D0%BE%D0%B9%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82%2C%20%D0%BC%D0%BE%D0%B3%D0%BB%D0%B8%20%D0%B8%D1%85%20%D1%81%D0%BF%D1%83%D1%82%D0%B0%D1%82%D1%8C.) например рекомендации от oracle. на мой взгляд они логично объясняют

2023-05-22 12:29 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +        "closed"
Здесь оставил исключительно, чтобы не потерять, удалить можно в любой момент

2023-05-22 12:30 UTC, valvandor commented on backend/db/models_configuration/models.py
>      service_id: Mapped[int] = mapped_column(primary_key=True)
ну в целом и сайт для презентации предметов продажи)

2023-05-22 12:36 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    users_mail: Mapped[str] = mapped_column(nullable=False)
ну то есть можно оставить просто first_name и т.д. 
=)

2023-05-22 12:50 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      client_request_id: Mapped[int] = mapped_column(primary_key=True)
https://www.sqlstyle.guide/#tables
Рекомендуют собирательное имя или, что менее предпочтительно - множественное число.
Use a collective name or, less ideally, a plural form. For example (in order of preference) staff and employees.
И даже если делаем во множественном числе имена таблиц, то почему модели тогда в единственном? Что нам это даст?

2023-05-22 12:56 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      users_id: Mapped[int] = mapped_column(primary_key=True)
А мы разве будем это где-то вовне демонстрировать?
Я так понимаю, что смысл применения uuid - это скрыть сколько пользователей на ресурсе. Тут же у нас в таблице только админы/сотрудники?

2023-05-22 13:10 UTC, valvandor commented on backend/db/models_configuration/models.py
>      client_request_id: Mapped[int] = mapped_column(primary_key=True)
при этом в примерах у него всё идёт во множественном числе) 
Модель как класс описывает сущность, а таблица это скорее про собирательный образ. Более логично на мой взгляд, когда именование таблицы во множественном числе: таблица "заказ" и таблица "заказов" — второй вариант мне кажется лучше. И если мы в "сырую" напишем какой-нибудь запрос, то второй вариант будет более наглядным: ``` select from orders .... ```

2023-05-22 13:13 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    theme: Mapped[int] = mapped_column(ForeignKey("service.service_id"))
Ну идея такая, что даже если клиент напишет неясное письмо, то хотя бы будет понятно откуда он сделал это обращение (если это было сделано через страницу какого-либо товара/услуги)

2023-05-22 13:14 UTC, valvandor commented on backend/db/models_configuration/models.py
>      users_id: Mapped[int] = mapped_column(primary_key=True)
имеется ввиду для всех идентификаторов выбрать uuid4 — так будет более унифицировано касательно этого и точно неповторяемо

2023-05-22 13:16 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        "closed"
ну потом мы это добавим, просто так получается что докстринг не соответствует описанию модели — ведь хранить мы может в этом поле что угодно. К тому же, если вдруг появятся какое-то новое значение, то вряд-ли этот докстринг будет актуальным

2023-05-22 16:29 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      users_id: Mapped[int] = mapped_column(primary_key=True)
Что-то в стиле:
from uuid import uuid4
from sqlalchemy.dialects.postgresql import UUID
sale_item_id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
?
PS Не очевидна выгода от исользования uuid, по мне primary_key=True и так генерит неповторяющиеся ключи

2023-05-22 16:30 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +        "closed"
Ok! Удалил

2023-05-22 16:34 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    theme: Mapped[int] = mapped_column(ForeignKey("service.service_id"))
Теперь theme: 
tittle: Mapped[str] - просто текстовое поле

2023-05-23 10:38 UTC, valvandor commented on backend/db/models_configuration/models.py
>      users_id: Mapped[int] = mapped_column(primary_key=True)
первичный ключ накладывает ограничения, самое важное это unique в нём. 
только для default надо вызвать эту функцию и преобразовать в строку, т.е. либо uuid4().hex или str(uuid4())
В принципе можно использовать отдельный тип данных, коли он предусмотрен для postgres'a

2023-05-23 17:47 UTC, valvandor requested changes

2023-05-23 17:47 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        default=uuid4, primary_key=True, unique=True)
uuid4 это функция. корректно будет str(uuid4())

2023-05-23 17:47 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        default=uuid4, primary_key=True, unique=True)
primary key уже накладывает ограничение  unique для поля — дублировать излишне

2023-05-23 17:47 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    trade_items_uid: Mapped[str] = mapped_column(
здесь указано название во множественном числе, это несколько логически неверно. Давай для ID-ов указывать имена от название таблицы в единственном числе с суффиксом `_id `

2023-05-23 17:47 UTC, valvandor commented on backend/db/models_configuration/models.py
> +    trade_items_name: Mapped[str] = mapped_column(nullable=False)
здесь пожалуй лучше оставить просто `name` — таблица сама за себя говорит и она однозначная на мой взгляд

2023-05-23 17:47 UTC, valvandor commented on backend/db/models_configuration/models.py
>      Services table
неактульный докстринг

2023-05-23 17:47 UTC, valvandor commented on backend/db/alembic/versions/959ee02cfa83_tab_01.py
> +    # ### end Alembic commands ###
кажется автогенерация alembic'а сработала нехорошо

2023-05-23 17:47 UTC, valvandor commented on backend/db/alembic/versions/959ee02cfa83_tab_01.py
> +down_revision = '75f62829631f'
для первой миграции по идее это значение должно быть None

2023-05-23 18:16 UTC, pillager-SB commented on backend/db/alembic/versions/959ee02cfa83_tab_01.py
> +down_revision = '75f62829631f'
Пока так, когда примем все поправки создам одну единственную миграцию

2023-05-23 18:17 UTC, pillager-SB commented on backend/db/alembic/versions/959ee02cfa83_tab_01.py
> +    # ### end Alembic commands ###
Не, это штатная работа алембика, нет переименования столбцов,только удаление и создание новых

2023-05-23 18:17 UTC, pillager-SB commented on backend/db/models_configuration/models.py
>      Services table
переделал

2023-05-23 18:18 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    trade_items_name: Mapped[str] = mapped_column(nullable=False)
оставил name

2023-05-23 18:18 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +    trade_items_uid: Mapped[str] = mapped_column(
Моя ошибка, вставил не глядя имя таблицы. Исправил

2023-05-23 18:21 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +        default=uuid4, primary_key=True, unique=True)
, unique=True убрал, Но вот при создании поля этот констрикт прописывался в алембике явно.

2023-05-23 18:58 UTC, pillager-SB commented on backend/db/models_configuration/models.py
> +        default=uuid4, primary_key=True, unique=True)
Не нашел прямых примеров, как это записывать в DeclarativeBase стиле, были варианты и без скобок.
Скобки добавил.

2023-05-23 18:58 UTC, valvandor requested changes

2023-05-23 18:58 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        default=uuid4(), primary_key=True)
`uuid4()` — это объект типа UUID. Во избежание ошибок лучше явно передавать значение строки: либо uuid4().hex или str(uuid4())

2023-05-23 19:00 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        default=uuid4(), primary_key=True)
или же можно попробовать сделать поле типа UUID как до этого было в одной из версий

2023-05-23 19:02 UTC, valvandor commented on backend/db/models_configuration/models.py
> +        default=uuid4, primary_key=True, unique=True)
возможно я ошибаюсь тогда, но судя по другим значениям вроде как передаётся значение а не коллбэк

2023-07-02 18:32 UTC, closed without merging